inherit_gem:
  simplycop: .simplycop.yml

AllCops:
  TargetRubyVersion: 3.1.2
  Rails:
    Enabled: false
  Documentation:
    Enabled: false
Metrics/BlockLength:
  Max: 250
Metrics/AbcSize:
  Max: 25
Metrics/MethodLength:
  Max: 25


