name: "Deploy Status Action"
description: "Check if the deployment is blocked"
author: "simplybusiness"
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.1
      - run: bundle exec ruby lib/action.rb
branding:
  icon: filter
  color: red
